Add unit tests (#11)
* Finish configuring jest to work with node, eslint, etc.

* Add unit tests to git hooks

* Add unit tests for SnaarfBot class

diff --git a/.githooks/pre-receive b/.githooks/pre-receive
--- a/.githooks/pre-receive
+++ b/.githooks/pre-receive
@@ -10,49 +10,59 @@ RED="\033[0;41m"
 NOFORMAT="\033[0m"
 
 if [[ "$STAGED_FILES" = "" ]]; then
-  exit 0
+
+  echo -e "\n${GREEN}Validating Javascript:${NOFORMAT}\n"
+
+  echo -e "${GREEN}Checking for eslint executable${NOFORMAT}"
+  ls $ESLINT_PATH &> /dev/null
+  if [[ "$?" == 1 ]]; then
+    echo -e "\t${RED}eslint not found. Please run 'npm install'${NOFORMAT}"
+    exit 1
+  fi
+  echo -e "${GREEN}eslint executable FOUND!${NOFORMAT}"
+
+  echo -e "${GREEN}Checking for prettier executable${NOFORMAT}"
+  ls $PRETTIER_PATH &> /dev/null
+  if [[ "$?" == 1 ]]; then
+    echo -e "\t${RED}prettier not found. Please run 'npm install'${NOFORMAT}"
+    exit 1
+  fi
+  echo -e "${GREEN}prettier executable FOUND!${NOFORMAT}"
+
+  echo -e "${GREEN}Running eslint on modified files${NOFORMAT}"
+  echo -e "$STAGED_FILES" | xargs npm run lint:check
+  if ! $PASS; then
+    echo -e "${RED}COMMIT FAILED:${NOFORMAT} Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
+    exit 1
+  fi
+  echo -e "${GREEN}ESLint check complete${NOFORMAT}"
+
+  echo -e "${GREEN}Running prettier on modified files${NOFORMAT}"
+  echo -e "$STAGED_FILES" | xargs npm run format:check
+
+  if [[ "$?" == 0 ]]; then
+    echo -e "${GREEN}prettier completed successfully${NOFORMAT}"
+  else
+    echo -e "${RED}prettier Failed${NOFORMAT}"
+    echo -e "${RED}COMMIT FAILED:${NOFORMAT} Your commit contains files do not conform to coding standards. Try running 'npm run format:write'. Please fix prettier errors and try again.\n"
+    exit 1
+  fi
+
+  echo -e "${GREEN}Javascript validation completed!${NOFORMAT}"
 fi
 
-PASS=true
+# UNIT TESTS
 
-echo -e "\n${GREEN}Validating Javascript:${NOFORMAT}\n"
+echo -e "${GREEN}Running jest on all unit tests${NOFORMAT}"
+npm test
 
-echo -e "${GREEN}Checking for eslint executable${NOFORMAT}"
-ls $ESLINT_PATH &> /dev/null
-if [[ "$?" == 1 ]]; then
-  echo -e "\t${RED}eslint not found. Please run 'npm install'${NOFORMAT}"
+if [[ "$?" != 0 ]]; then
+  echo -e "${RED}jest Failed${NOFORMAT}"
+  echo -e "${RED}COMMIT FAILED:${NOFORMAT} Unit tests are failing on your branch. Please see the test output and fix any issues. You can try checking out 'main' and running 'npm test' to check whether it's your code.\n"
   exit 1
 fi
-echo -e "${GREEN}eslint executable FOUND!${NOFORMAT}"
 
-echo -e "${GREEN}Checking for prettier executable${NOFORMAT}"
-ls $PRETTIER_PATH &> /dev/null
-if [[ "$?" == 1 ]]; then
-  echo -e "\t${RED}prettier not found. Please run 'npm install'${NOFORMAT}"
-  exit 1
-fi
-echo -e "${GREEN}prettier executable FOUND!${NOFORMAT}"
-
-echo -e "${GREEN}Running eslint on modified files${NOFORMAT}"
-echo -e "$STAGED_FILES" | xargs npm run lint:check
-if ! $PASS; then
-  echo -e "${RED}COMMIT FAILED:${NOFORMAT} Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
-  exit 1
-fi
-echo -e "${GREEN}ESLint check complete${NOFORMAT}"
-
-echo -e "${GREEN}Running prettier on modified files${NOFORMAT}"
-echo -e "$STAGED_FILES" | xargs npm run format:check
-
-if [[ "$?" == 0 ]]; then
-  echo -e "${GREEN}prettier completed successfully${NOFORMAT}"
-else
-  echo -e "${RED}prettier Failed${NOFORMAT}"
-  echo -e "${RED}COMMIT FAILED:${NOFORMAT} Your commit contains files do not conform to coding standards. Try running 'npm run format:write'. Please fix prettier errors and try again.\n"
-  exit 1
-fi
-
-echo -e "${GREEN}Javascript validation completed!${NOFORMAT}"
+echo -e "${GREEN}jest unit tests PASSED${NOFORMAT}"
 
 if [[ "$?" == 0 ]]; then
   echo -e "${GREEN}COMMIT SUCCEEDED${NOFORMAT}\n"
